# Generated by Django 5.1.1 on 2024-09-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tokoentry_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokoEntry',
            new_name='ItemEntry',
        ),
    ]
