# Generated by Django 5.1.1 on 2024-09-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_tokoentry_itementry'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementry',
            name='image',
            field=models.URLField(default='https://imgur.com/j6W2Ko4'),
            preserve_default=False,
        ),
    ]
